# Dependabot configuration file
version: 2  # Specify the version of the Dependabot configuration

updates:
  # Configuration for GitHub Actions dependencies
    # Specify the ecosystem for GitHub Actions
  - package-ecosystem: "github-actions"  # Specify the ecosystem for GitHub Actions
    directory: "/"  # Root directory of the repository
    schedule:
      interval: "daily"  # Check for updates daily
    target-branch: "dev"  # Target branch for updates
    ignore:
      - dependency-name: "actions/checkout"  # Ignore specific versions of actions/checkout
        versions: ["2.x"]
      - dependency-name: "actions/setup-python"  # Ignore specific versions of actions/setup-python
        versions: ["2.x", "3.x", "4.x"]

  # Configuration for GitHub Actions dependencies for the master branch
  # Specify the ecosystem for GitHub Actions
  - package-ecosystem: "github-actions"  # Specify the ecosystem for GitHub Actions
    directory: "/"  # Root directory of the repository
    schedule:
      interval: "daily"  # Check for updates daily
    target-branch: "master"  # Target branch for updates
    ignore:
      - dependency-name: "actions/checkout"  # Ignore specific versions of actions/checkout
        versions: ["2.x"]
      - dependency-name: "actions/setup-python"  # Ignore specific versions of actions/setup-python
        versions: ["2.x", "3.x", "4.x"]

  # Configuration for Python dependencies managed by pip
  - package-ecosystem: "pip"  # Specify the ecosystem for pip (Python)
    directory: "/"  # Root directory of the repository
    schedule:
      interval: "daily"  # Check for updates daily
