name: CLI Tool Test

# This workflow tests for the intended behavior of the CLI tool

on: [push, pull_request]

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Build Package
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        python -m build


    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install package
      # Install the package in the virtual environment from the newly built wheel file
      run: |
        source venv/bin/activate
        pip install dist/*.whl

    - name: Test CLI tool
      run: |
        source venv/bin/activate
        input_file=tests/test_files/WWARA-rptrlist-TEST.csv
        output_file=tests/test_files/test_output.csv
        reference_output_file=tests/test_files/reference_output.csv

        wwara_chirp $input_file $output_file

        if [ ! -f $output_file ]; then
          echo "Output file not created"
          exit 1
        fi

        if ! diff -q $output_file $reference_output_file; then
          echo "Output file does not match reference output"
          diff -q $output_file $reference_output_file
          exit 1
        fi

        echo "CLI tool test passed"

    # check for the presence of --help flag in the CLI tool
    - name: Test CLI tool help flag
      run: |
        source venv/bin/activate
        wwara_chirp --help > help_output.txt
        if ! grep -q "WWARA CHIRP Export Script Update" help_output.txt; then
          echo "CLI tool help flag test failed"
          exit 1
        fi
        
