name: Test CLI tool on published package

# This workflow tests for the intended behavior of the CLI tool

on:
  pull_request:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  test-cli:
    runs-on: ubuntu-latest

    env:
      input_file: tests/test_files/WWARA-rptrlist-TEST.csv
      output_file: tests/test_files/test_output.csv
      reference_output_file: tests/test_files/reference_output.csv

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup pip
      run: |
        python -m pip install --upgrade pip

    - name: Install package
      run: |
        pip install --pre --extra-index-url https://test.pypi.org/simple/ wwara-chirp
        echo
        echo "****************************************************"
        echo "which wwara_chirp"
        which wwara_chirp
        echo "wwara_chirp --version"
        wwara_chirp --version
        python3 -m pip show wwara_chirp

    - name: Check sample test and reference files
      run: |
        grep K4LED ${{ env.input_file }}
        grep K4LED ${{ env.reference_output_file }}
        

    - name: Test CLI tool
      run: |

        wwara_chirp ${{ env.input_file }} ${{ env.output_file }}

        if [ ! -f ${{ env.output_file }} ]; then
          echo "Output file not created"
          exit 1
        fi

        if ! diff -q ${{ env.output_file }} ${{ env.reference_output_file }}; then
          echo "Output file does not match reference output"
          diff -q ${{ env.output_file }} ${{ env.reference_output_file }}
          exit 1
        fi

        echo "CLI tool test passed"

    - name: Test CLI tool help flag
      run: |
        wwara_chirp --help > help_output.txt
        cat help_output.txt
        if ! grep -q "WWARA CHIRP Export Script Update" help_output.txt; then
          echo "CLI tool help flag test failed"
          exit 1
        fi
        
    - name: Print wwara-chirp.log
      if: always() # Ensures this step runs even if previous steps fail
      run: |
        if [ -f wwara-chirp.log ]; then
          echo "Contents of wwara-chirp.log:"
          cat wwara-chirp.log
        else
          echo "wwara-chirp.log not found."
        fi